project:
  output-dir: _site
  render:
    - "index.qmd"
    - "publications/"
    - "projects/"
    - "blog/"
    - "en/"
    - "!es/"

website:
  description: "Postdoc Researcher in XAI and Foundation Models at RWTH Aachen University"

  navbar:
    left:
      - text: "Home"
        href: en/index.qmd
      - text: "Experience"
        href: en/experience.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Research and Projects"
        href: projects/index.qmd
      - text: "Teaching"
        href: en/teaching.qmd
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=BnCVQsUAAAAJ
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/andresfp14
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/andresfelipeposadamoreno/
        aria-label: LinkedIn
      - icon: translate
        text: "ES"
        href: /es/
        aria-label: Versión en español

  page-footer:
    left: |
      &copy; 2025 Andres Felipe Posada Moreno. Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
    right: |
      Built with [Quarto](https://quarto.org/).
