project:
  type: website
  render:
    - "!CONTENT_INVENTORY.md"
    - "!LICENSE.md"
    - "!README.md"
    - "!contact.qmd"

website:
  title: "Andres Felipe Posada Moreno"
  site-url: "https://andresfp14.github.io/"

  search:
    location: navbar
    type: overlay

format:
  html:
    page-layout: full
    theme:
      light: [cosmo, styles/custom.scss]
    toc: true
    toc-depth: 3
